---
title: "Cute penguins"
format: 
  docx:
    reference-doc:  F:/Aktenschrank/Analysen/R/Rtemplate1.docx
    toc: true
  pdf:
    toc: true
editor: visual
execute: 
  echo: false
  warning: false
  output: asis
fig-dpi: 300
fig-width: 6
fig-height: 8
tbl-cap-location: top
---

```{r setupstuff}
pacman::p_load(conflicted,tidyverse,wrappedtools,
               palmerpenguins, rlist, flextable,
               patchwork, ggbeeswarm, ggsignif)
conflicts_prefer(dplyr::filter, dplyr::select)
set_flextable_defaults(big.mark = " ", 
                       font.size = 9, 
                       theme_fun = theme_vanilla,
                       padding.bottom = 1, 
                       padding.top = 3,
                       padding.left = 3,
                       padding.right = 4
)
theme_set(theme_bw())
```

```{r dataprep}
rawdata <- penguins |>
  drop_na() |> 
  mutate(year=factor(year))
Adelies <- rawdata |> 
  filter(species == "Adelie")
gauss_vars <- ColSeeker(rawdata,"_")
ord_vars <- ColSeeker(rawdata,"_")
fact_vars <- ColSeeker(rawdata,c("sp","is"))
```

# Gaussian
## Single variable
```{r}
t_out <- t_var_test(body_mass_g~sex, data = Adelies)
dens_plot <- Adelies |> 
  ggplot(aes(body_mass_g, fill=sex))+
  geom_density(alpha=.5)
summary_plot <- Adelies |> 
  ggplot(aes(sex, body_mass_g))+
  geom_beeswarm(alpha=.1)+
  stat_summary(fun.data = mean_cl_normal,
               color="darkorange")+
  geom_signif(comparisons=list(c(1,2)),
              annotations=paste("p",
                                formatP(t_out$p.value,
                                        pretext = T,
                                        mark = T)))+
  scale_y_continuous("Mean body mass (g) \u00b1 95% CI",
                     expand=expansion(mult=c(.05,.1)))
dens_plot/summary_plot
```

## Multiple variables
```{r}
gauss_results <- compare2numvars(Adelies, 
                                 gauss_vars$names,
                                 'sex',T)
gauss_results |>
  flextable() |> 
  set_table_properties(width = .75)
```

```{r}
#| fig-height: 4
for(row_i in seq_along(gauss_results$Variable)){
  plot_temp <- Adelies |> 
    ggplot(aes(sex,.data[[gauss_results$Variable[row_i] |> 
                            as.character()]]))+
  geom_beeswarm(alpha=.1)+
  stat_summary(fun.data = mean_cl_normal,
               color="orangered3")+
  geom_signif(comparisons=list(c(1,2)),
              annotations=paste("p",
                                formatP(gauss_results$p[row_i],
                                        pretext = T,
                                        mark = T)))+
  scale_y_continuous(paste(gauss_results$Variable[row_i],
                           "\u00b1 95% CI"),
                     expand=expansion(mult=c(.05,.1)))
  
  print(plot_temp)
  cat("<br>\n\n")
}
```


# Ordinal
## Single variable
```{r}
w_out <- wilcox.test(body_mass_g~sex, data = Adelies)
dens_plot <- Adelies |> 
  ggplot(aes(body_mass_g, fill=sex))+
  geom_density(alpha=.5)
summary_plot <- Adelies |> 
  ggplot(aes(sex, body_mass_g))+
  geom_boxplot(outlier.alpha = 0)+
  geom_beeswarm(alpha=.1)+
  geom_signif(comparisons=list(c(1,2)),
              annotations=paste("p",
                                formatP(w_out$p.value,
                                        pretext = T,
                                        mark = T)))+
  scale_y_continuous("Body mass (g)",
                     expand=expansion(mult=c(.05,.1)))
dens_plot/summary_plot
```

## Multiple variables
```{r}
ord_results <- compare2numvars(Adelies, 
                                 ord_vars$names,
                                 'sex',F)
ord_results |>
  flextable() |> 
  set_table_properties(width = 1)
```

```{r}
#| fig-height: 4
for(row_i in seq_along(ord_results$Variable)){
  plot_temp <- Adelies |> 
    ggplot(aes(sex,.data[[ord_results$Variable[row_i] |> 
                            as.character()]]))+
    geom_boxplot(outlier.alpha = 0)+
    geom_beeswarm(alpha=.1)+
    geom_signif(comparisons=list(c(1,2)),
                annotations=paste("p",
                                  formatP(ord_results$p[row_i],
                                          pretext = T,
                                          mark = T)))+
    scale_y_continuous(paste(gauss_results$Variable[row_i]),
                       expand=expansion(mult=c(.05,.1)))
  
  print(plot_temp)
  cat("<br>\n\n")
}
```

# Categoricals
## Single variable
```{r}
fisher_out_sex <- fisher.test(rawdata$species, rawdata$sex)

ggplot(rawdata,aes(sex,fill=species))+
  geom_bar()+
  geom_text(stat="count",aes(label=after_stat(count)),
            position=position_stack(vjust=.5))+
  geom_signif(comparisons=list(c(1,2)),
              aes(y=175),
              annotations=paste("p",
                                markSign(
                                  fisher_out_sex$p.value)))+
  scale_y_continuous(expand=expansion(mult=c(.05,.1)))


fisher_out_island_v1 <- fisher.test(rawdata$species,
                                    rawdata$island,
                                    workspace = 10^7)
fisher_out_island_v2 <- fisher.test(rawdata$species,
                                    rawdata$island,
                                    simulate.p.value = T,
                                    B = 10^4)


fisher_out <- fisher.test(rawdata$species, rawdata$island,
                          workspace = 10^7)
fisher_out2 <- fisher.test(rawdata$species, rawdata$island,
                          simulate.p.value = T,
                          B = 10^4)
ggplot(rawdata,aes(island,fill=species))+
  geom_bar()+
  geom_text(stat="count",aes(label=..count..),
            position=position_stack(vjust=.5))
```


